### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by michaelfolkson**

### CODE REVIEW

**Comment by kanzure** [comment]
We'll need to figure out a plan for the redirects... What about the non-bitcoin transcripts?

**Comment by michaelfolkson** [comment]
Yeah good question. Maybe don't have redirects and maintain your site? I could just copy over existing Bitcoin transcripts to a new repo. Or only redirect the Bitcoin transcripts that are hosted by the new site? What happens to the existing site is obviously entirely down to you. I don't think it makes sense for the new Bitcoin Transcripts site to have transcripts on genetics etc however interesting.

**Comment by michaelfolkson** [comment]
But this README could be the README for the new repo and not be used here. If that's the case let me know and I/you can close this pull request. Or I could change the README to be specific to this repo (non-Bitcoin transcripts etc) before merging it.

**Comment by kanzure** [comment]
figuring out a redirects proposal at the moment.

**Comment by kanzure** [comment]
I think this is the list of transcripts you want to have redirects? https://diyhpl.us/~bryan/bitcoin/bitcoin-transcripts.txt

**Comment by michaelfolkson** [comment]
Files that aren’t Bitcoin related and won’t be hosted on Bitcoin Transcripts site

In /diyhpluswiki/transcripts. All external directories are not needed either.

2009-09-15-paul-rothemund.mdwn
2009-09-16-chris-paredis.mdwn
2017-01-26-george-church.mdwn
2018-02-11-ascendance-biomedical-update.mdwn
2018-02-21-iarpa-mist.mdwn
2018-05-21-enhanced-humans-risks-opportunities.mdwn
agi-16/deep-learning-for-agi-survey-of-recent-developments.mdwn
agi-16/deep-neural-networks-cant-make-agi.mdwn
baidu-deep-learning-for-speech-recognition.mdwn
biohacktheplanet/2018/aggressively-growing-trees.mdwn
biohacktheplanet/2018/ai-vs-the-brain.mdwn
biohacktheplanet/2018/creating-a-community-of-biohackers.mdwn
biohacktheplanet/2018/day-two.mdwn
biohacktheplanet/2018/i-am-a-biohacker.mdwn
biohacktheplanet/2018/more-than-just-dna.mdwn
biohacktheplanet/2018/the-future-of-biotech.mdwn
biohacktheplanet/2018/tristan-roberts-patti-zettler.mdwn
biohacktheplanet/2019/ageing-as-a-disease.mdwn
biohacktheplanet/2019/biohacking-hollywood.mdwn
biohacktheplanet/2019/creating-communities.mdwn
biohacktheplanet/2019/daria-dantseva.mdwn
biohacktheplanet/2019/glybera.mdwn
biohacktheplanet/2019/state-of-union.mdwn
bodyhackingcon/2019/brian-bushway.mdwn
bodyhackingcon/2019/introduction.mdwn
diy-human-gene-therapy-with-crispr.mdwn
ed-boyden-engineering-revolutions.mdwn
fbi-diybio-2011/2011-07-13.txt
fbi-diybio-2012/avery-louie-bosslab.mdwn
fbi-diybio-2012/berlin.mdwn
fbi-diybio-2012/biologigaragen.mdwn
fbi-diybio-2012/brian-degger.mdwn
fbi-diybio-2012/carlo-quinonez.mdwn
fbi-diybio-2012/chicago-open-science.mdwn
fbi-diybio-2012/chris-anderson-syncberc.mdwn
fbi-diybio-2012/dan-grushkin-genspace.mdwn
fbi-diybio-2012/denisa-kera.mdwn
fbi-diybio-2012/derek-jacoby.mdwn
fbi-diybio-2012/ellen-jorgensen-genspace.mdwn
fbi-diybio-2012/finnish.mdwn
fbi-diybio-2012/funkenstein.mdwn
fbi-diybio-2012/genoblasts.mdwn
fbi-diybio-2012/howard-simon-dna20.mdwn
fbi-diybio-2012/intro.mdwn
fbi-diybio-2012/jacob-shiach.mdwn
fbi-diybio-2012/joseph-jackson.mdwn
fbi-diybio-2012/julie-sohn-fbi-outreach.mdwn
fbi-diybio-2012/kristina-hathaway-biocurious.mdwn
fbi-diybio-2012/london-hackspace.mdwn
fbi-diybio-2012/mac-cowell.mdwn
fbi-diybio-2012/madlab.mdwn
fbi-diybio-2012/marc-juul.mdwn
fbi-diybio-2012/max-hodack-gene-synthesis.mdwn
fbi-diybio-2012/meg-flanagan-department-of-state.mdwn
fbi-diybio-2012/metu-biogene.mdwn
fbi-diybio-2012/micronation-natural-fiber.mdwn
fbi-diybio-2012/nancy-burgess-dtra.mdwn
fbi-diybio-2012/outreach-session.mdwn
fbi-diybio-2012/piers-millett.mdwn
fbi-diybio-2012/pieter-van-boheemen.mdwn
fbi-diybio-2012/rachael-turner-madlab.mdwn
fbi-diybio-2012/radka-chido-haneckova.mdwn
fbi-diybio-2012/romie-littrell.mdwn
fbi-diybio-2012/rudiger-trojok.mdwn
fbi-diybio-2012/sascha-karberg.mdwn
fbi-diybio-2012/security-issues-session.mdwn
fbi-diybio-2012/synbiota.mdwn
fbi-diybio-2012/thomas-landrain-la-paillasse.mdwn
fbi-diybio-2012/todd-kuiken-woodrow-wilson.mdwn
fbi-diybio-2012/todd-san-diego.mdwn
forbes/30under30/2019/a16z.mdwn
forbes/30under30/2019/auto-industry-blockchain-competition.mdwn
forbes/30under30/2019/motor-city-blockchain.mdwn
forbes/30under30/2019/ryan-breslow.mdwn
hgp-write/2016-05-10/de-novo-chromosomes-that-shuttle-between-yeast-and-mammalian-systems.mdwn
hgp-write/2016-05-10/from-recoli-to-1-million-genomes.mdwn
hgp-write/2016-05-10/haploid-embryonic-stem-cells.mdwn
hgp-write/2016-05-10/overview.mdwn
hgp-write/2016-05-10/recoding-ecoli-to-57-codons.mdwn
hgp-write/2016-05-10/seven-signals-toolbox-cell-tissue-therapies.mdwn
hgp-write/2016-05-10/synthesizing-a-prototrophic-human-genome.mdwn
hgp-write/2016-05-10/synthetic-yeast-genome-project-lessons-learned.mdwn
hgp-write/2016-05-10/transplantation.mdwn
hgp-write/2016-05-10/ultra-safe-cell-line.mdwn
hgp-write/2017-05-09/announcements.mdwn
hgp-write/2017-05-09/assembling-centromeres-in-silico.mdwn
hgp-write/2017-05-09/biologically-inspired-engineering-of-microorganisms.mdwn
hgp-write/2017-05-09/center-of-excellence-for-engineering-biology.mdwn
hgp-write/2017-05-09/delivering-big-dna-to-mammalian-cells.mdwn
hgp-write/2017-05-09/dnascript.mdwn
hgp-write/2017-05-09/ethical-frameworks-for-hgp-write.mdwn
hgp-write/2017-05-09/evolution-and-progress-of-hgp-write.mdwn
hgp-write/2017-05-09/framing-and-addressing-the-ethical-issues-raised-by-hgp-write.mdwn
hgp-write/2017-05-09/hgp-write-scientific-executive-committee-panel-discussion.mdwn
hgp-write/2017-05-09/human-artificial-chromosomes.mdwn
hgp-write/2017-05-09/josh-leonard.mdwn
hgp-write/2017-05-09/lessons-learned-from-reading-human-genomes.mdwn
hgp-write/2017-05-09/microarray-flow-cell-oligos-dna-synthesis.mdwn
hgp-write/2017-05-09/mistakes-were-made-sc2.mdwn
hgp-write/2017-05-09/molecular-assemblies.mdwn
hgp-write/2017-05-09/musebio.mdwn
hgp-write/2017-05-09/octopus-genome-insights.mdwn
hgp-write/2017-05-09/organoids.mdwn
hgp-write/2017-05-09/overview.mdwn
hgp-write/2017-05-09/precision-human-genome-engineering-of-disease-associated-noncoding-variants.mdwn
hgp-write/2017-05-09/rational-engineering-of-bacterial-consortia-with-the-gut-microbiome.mdwn
hgp-write/2017-05-09/recombinase-mediated-assembly-and-isothermal-amplification-arrays.mdwn
hgp-write/2017-05-09/redesign-of-yeast-chromosome-and-potential-application.mdwn
hgp-write/2017-05-09/synthetic-genomics-tRNA-neochromosome.mdwn
hgp-write/2017-05-09/synthetic-regulatory-genomics.mdwn
hgp-write/2017-05-09/synthetic-screening-for-essential-introns-and-retroelements-in-human-and-animal-cells.mdwn
hgp-write/2017-05-09/technology-for-the-construction-of-synthetic-bacteria.mdwn
hgp-write/2017-05-09/ultrasafe-cell-line.mdwn
hgp-write/2017-05-09/understanding-plants-for-human-and-environmental-use.mdwn
hgp-write/2017-05-09/unlock-the-power-of-scramble-with-rescues.mdwn
hgp-write/2017-05-09/virginia-cornish.mdwn
hgp-write/2017-05-09/working-group-roadmap-bioinformatics.mdwn
hgp-write/2017-05-09/working-group-roadmap-intellectual-property-mpegla.mdwn
hgp-write/2017-05-09/working-group-roadmap-safety-engineering.mdwn
hgp-write/2017-05-09/working-group-roadmap-social-legal-and-ethical-issues.mdwn
hgp-write/2017-05-09/working-group-roadmap-technology-and-infrastructure-development.mdwn
hgp-write/2017-05-09/wrap-up-and-next-steps.mdwn
hgp-write/2017-05-09/xenotransplantation.mdwn
hplus-summit-2009/alex-lightman.mdwn
hplus-summit-2009/andrew-hessel.mdwn
hplus-summit-2009/anselm-levksaya.mdwn
hplus-summit-2009/aubrey-de-grey.mdwn
hplus-summit-2009/christine-peterson.mdwn
hplus-summit-2009/david-pearce.mdwn
hplus-summit-2009/dylan-morris.mdwn
hplus-summit-2009/edward-miller.mdwn
hplus-summit-2009/fahy.mdwn
hplus-summit-2009/greg-benford.mdwn
hplus-summit-2009/ken-hayworth.mdwn
hplus-summit-2009/patri-friedman.mdwn
hplus-summit-2009/sonia-arrison.mdwn
hplus-summit-2009/todd-huffman.mdwn
hplus-summit-2010/d1s0-david-orban
hplus-summit-2010/d1s1-1-noah-goodman
hplus-summit-2010/d1s1-2-andrea-kuszewski
hplus-summit-2010/d1s1-3-andrew-hessel
hplus-summit-2010/d1s1-4-melanie-swan
hplus-summit-2010/d1s1-5-ramez-naam
hplus-summit-2010/d1s1-6-ronald-bailey
hplus-summit-2010/d1s1-alex-lightman
hplus-summit-2010/d1s10-millie-ray
hplus-summit-2010/d1s11-john-smart
hplus-summit-2010/d1s15-greenstein
hplus-summit-2010/d1s16-tim-marzullo
hplus-summit-2010/d1s2-ed-boyden
hplus-summit-2010/d1s3-lauren-silbert-greg-stephens-uri-hasson
hplus-summit-2010/d1s4-alex-backer
hplus-summit-2010/d1s5-alexandra-elbakyan
hplus-summit-2010/d1s9-mikhail-shapiro
hplus-summit-2010/d2-ray-kurzweil.html
hplus-summit-2010/d2s0-alex-lightman.html
hplus-summit-2010/d2s1-aubrey-de-grey.html
hplus-summit-2010/d2s11-noah-bushnell.html
hplus-summit-2010/d2s12-robert-tercek.html
hplus-summit-2010/d2s13-tony-greenberg.html
hplus-summit-2010/d2s14-natasha-vita-more.html
hplus-summit-2010/d2s16-mark-hatch.html
hplus-summit-2010/d2s17-david-orban.html
hplus-summit-2010/d2s2-morris-johnson.html
hplus-summit-2010/d2s3-george-dvorsky.html
hplus-summit-2010/d2s7-heather-schlegel.html
human-genome-editing-summit/2018-hong-kong/carrie-lam.mdwn
human-genome-editing-summit/2018-hong-kong/genes-genomes-genetic-variation.mdwn
human-genome-editing-summit/2018-hong-kong/george-daley-genome-editing-pathways-to-translation.mdwn
human-genome-editing-summit/2018-hong-kong/intro.mdwn
human-genome-editing-summit/2018-hong-kong/jiankui-he-human-genome-editing.mdwn
human-genome-editing-summit/2018-hong-kong/junjiu-huang-beta-thalassemia-embryo-editing.mdwn
humanityplus-at-caltech/alex-peake-intelligence-amplification-ai
humanityplus-at-caltech/amy-li-iphones-ibrains.mdwn
letter-who-germline-genetic-engineering-2019-07-29.mdwn
markram-2006.mdwn
montclare-protein-engineering/directed-evolution.mdwn
nectome-1517-2018.mdwn
niac-2016/reconstituting-asteroids-into-mechnical-automata.mdwn
open-science-summit-2010/aiden-hollis-health-impact-fund.mdwn
open-science-summit-2010/andrew-hessel-pink-army.mdwn
open-science-summit-2010/christine-peterson.mdwn
open-science-summit-2010/cure-entrepreneurs.mdwn
open-science-summit-2010/diybio-bioethics-commission.mdwn
open-science-summit-2010/diybio-qa.mdwn
open-science-summit-2010/drug-dev-pipeline-qa.mdwn
open-science-summit-2010/ed-you.mdwn
open-science-summit-2010/innovation-paradigm-qa.mdwn
open-science-summit-2010/introductions.mdwn
open-science-summit-2010/jamie-love-knowledge-ecology-international.mdwn
open-science-summit-2010/jason-bobe.mdwn
open-science-summit-2010/jonathan-izant-sage-bionetworks.mdwn
open-science-summit-2010/jorge-hirsch.mdwn
open-science-summit-2010/keith-bergelt-open-invent-network.mdwn
open-science-summit-2010/len.mdwn
open-science-summit-2010/mac-cowell.mdwn
open-science-summit-2010/meredith-patterson.mdwn
open-science-summit-2010/michael-nielsen-reinventing-discovery.mdwn
open-science-summit-2010/microfinancing-questions.mdwn
open-science-summit-2010/mydaughtersgenome.mdwn
open-science-summit-2010/raymond-mccauley.mdwn
open-science-summit-2010/rob-carlson.mdwn
open-science-summit-2010/scott-johnson-myelin-repair-foundation.mdwn
open-science-summit-2010/thursday.mdwn
open-science-summit-2011/andrew-torrance-open-and-closed-innovation.txt
open-science-summit-2011/intro.txt
open-science-summit-2011/joyce-peng-beijing-genomics-institute.txt
open-science-summit-2011/misha-angrist.txt
open-science-summit-2011/nick-shockey-open-access.txt
open-science-summit-2011/stephan-kinsella-ip-and-new-mercantilism.txt
open-science-summit-2011/victoria-stodden-transparency-in-scientific-discovery.txt
orca-2014/alexandra-kurland.mdwn
orca-2014/bailey.mdwn
orca-2014/kay-laurence.mdwn
orca-2014/ken-ramirez.mdwn
orca-2014/panksepp.mdwn
orca-2014/phung-luu.mdwn
orca-2014/steve-white.mdwn
pcsbi-2010/2010-07-08
pcsbi-2010/after_lunch_panel
pcsbi-2010/below_video_transcript
pcsbi-2010/final_panel.1
pcsbi-2010/final_panel.2
pcsbi-2010/panel.txt
pcsbi-2010/panel2.txt
pcsbi-2010/panel3.txt
pcsbi-2010/questions-session.1
singularity-summit-2009/anders-sandberg.mdwn
singularity-summit-2009/anna-salamon.mdwn
singularity-summit-2009/ed-boyden.mdwn
spacex/elon-musk-making-humans-a-multiplanetary-species.mdwn
startup-science-2012/carlo-quinonez.mdwn
startup-science-2012/elizabeth-iorns-science-exchange.mdwn
startup-science-2012/heather-piwowar-jason-priem.mdwn
startup-science-2012/intro.mdwn
startup-science-2012/jeremy-howard-margrit-zwimmer.mdwn
startup-science-2012/john-adler-cureus.mdwn
startup-science-2012/john-wilbanks.mdwn
startup-science-2012/kevin-lustig-assay-depot.mdwn
startup-science-2012/mark-kaganovich-solvebio.mdwn
startup-science-2012/max-hodak.mdwn
startup-science-2012/pete-binfield-peerj.mdwn
startup-science-2012/recap.mdwn
startup-science-2012/richard-price-academia.edu.mdwn
startup-science-2012/william-gunn-mendeley.mdwn
verifiable-brain-preservation.mdwn

**Comment by kanzure** [comment]
I need the list of files to redirect so that I can add that to the web server configuration. The files that you're not interested in would not be subject to redirects.

**Comment by kanzure** [comment]
I think you're going to need a system of classification and management for the transcripts. Probably some database would be ideal, so that you can display lists of transcripts with summaries for different views/categories/tags. Ikiwiki is technically capable of this, but you would have to dig into how to use its CSS-- you might have another web framework that you prefer of course, jekyll or maybe a small web application would be appropriate.

**Comment by michaelfolkson** [comment]
I'm planning to use Jekyll so I can base Bitcoin Transcripts on the https://bitcoincore.reviews/ site. But yes agreed classification is definitely going to be needed. On https://bitcoincore.reviews/ they group the review club sessions by date, PR number, component, host, author. 

>  I need the list of files to redirect so that I can add that to the web server configuration. The files that you're not interested in would not be subject to redirects.

Ok can I add the list of files to be redirected to this repo (in a .txt file)? That way I can add to the list whenever I add a new transcript to the repo. We'll both have read and write ability when it is in this repo. I'll open a PR adding the .txt file if that is ok?

**Comment by kanzure** [comment]
ok sure

**Comment by michaelfolkson** [comment]
Opened another PR #113  to add a placeholder for the finalized list of transcripts that need to be redirected. It doesn't make sense to keep updating it as new transcripts continue to be added to your repo. I will provide a finalized list when the new site is up and ready to receive redirects. 

Apart from that closing this PR as we don't need a README here if all GitHub activity will move to the new repo.

**Pull request closed without merging**
