### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by MaxHillebrand**
s/splash/slash

### CODE REVIEW

**Comment by michaelfolkson** [comment]
There are a number of typos across these transcripts (including ones done by me) but this isn't an example. "splashback" is referring to the block size drama having negative impacts. Hence I will close this.

https://dictionary.cambridge.org/dictionary/english/splashback

**Comment by kanzure** [comment]
Yeah maybe we should run spellcheck one of these days

**Comment by MaxHillebrand** [comment]
I see, thanks for clarifying @michaelfolkson - I didn't know about the use of splashback in this context.

**Comment by michaelfolkson** [comment]
No worries. If you find any other GMax wisdom scattered across the internet feel free to open a PR to add it (ideally in a similar format to how I added it)

**Comment by michaelfolkson** [comment]
I plan to go through [Bitcointalk](https://bitcointalk.org/index.php?action=profile;u=11425;sa=showPosts) and [Reddit](https://www.reddit.com/user/nullc) for his technical posts at some point.

**Pull request closed without merging**
