### PR TITLE
Create Lightning-network-layer-by-layer.mdwn

### PR DESCRIPTION
**Pull request by Caralie**

### CODE REVIEW

**Comment by michaelfolkson** [comment]
Thanks for this @Caralie! Bryan did a transcript for this talk in real time [here](https://github.com/kanzure/diyhpluswiki/blob/master/transcripts/scalingbitcoin/tel-aviv-2019/edgedevplusplus/lightning-network-routing.mdwn) but yours looks to be an improvement in terms of accuracy (not doing it in real time helps!)

(I think you missed it because you didn't save yours in the edgedevplusplus directory. But Bryan's title is a touch confusing too)

If you can save yours in the right directory (edgedevplusplus) then maybe we can delete Bryan's. We like to keep persistent links generally but given that the title is incorrect I think it is ok to delete it.

Can you update this PR by saving yours in the tel-aviv-2019/edgedevplusplus directory rather than merely the tel-aviv-2019 directory ? I'll deal with deleting Bryan's original.

**Comment by michaelfolkson** [comment]
I don't think I'll delete the link as Carla did do a talk on network routing too [here](https://www.youtube.com/watch?v=j2l_Ut4k1qI) but I don't think Bryan transcribed this talk.

**Comment by Caralie** [comment]
Thanks @michaelfolkson for walking me through that! That's exactly why I missed it. Sorry I overlooked the edgedevplusplus folder!

**Comment by kanzure** [comment]
So..... it looks like I was pretty far off. This might be fun to look at more closely.

**Comment by michaelfolkson** [comment]
@kanzure: Yeah a lot missing from Carla's talks at Dev++ for me, Caralie or someone else to add. 

@Caralie: Not important for this time and I don't want to keep nitpicking as I know you are new to Git(Hub) but try to keep your commit messages shorter. This one is unnecessarily is long

"Rename transcripts/scalingbitcoin/tel-aviv-2019/Lightning-network-layer-by-layer.mdwn to transcripts/scalingbitcoin/tel-aviv-2019/edgedevplusplus/Lightning-network-layer-by-layer.mdwn"

This [article](https://chris.beams.io/posts/git-commit/) provides some good advice on commit messages. If you follow this it will be appreciated on other open source projects that have more stringent criteria than our transcripts one.

**Comment by michaelfolkson** [comment]
I think this is good to merge

**Comment by Caralie** [comment]
Thanks @michaelfolkson - still learning best practices, so I'll incorporate the advice from the article moving forward!

**Pull request merged**
